export const CHANGE_INPUT_VALUE = 'change_input_value'
export const GET_TODOLIST_DATA = 'get_todolist_data'
export const INIT_TODOLIST = 'init_todolist'
export const ADD_TODO_ITEM = 'add_todo_item'
export const DELETE_TODO_ITEM = 'delete_todo_item'